import type { Metadata } from "next";       // Type for defining page metadata
import "./globals.css";                     // Global CSS styles
import { AppProvider } from "@/context/appContext"; // Context provider for global state
import { SocketProvider } from "@/context/SocketContext";

// --------------------- PAGE METADATA ---------------------
export const metadata: Metadata = {
  title: "MoodVibe Chat",                 // Title of the website
  description: "Generated by create next app", // Meta description
};

// --------------------- ROOT LAYOUT ---------------------
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;              // Any nested components/pages
}>) {
  return (
    <html lang="en">
      {/* AppProvider wraps the entire app to provide global state */}
      <body>
        <AppProvider>
          <SocketProvider>
            {children} {/* Render the page content here */}
          </SocketProvider>
        </AppProvider>
      </body>
    </html>
  );
}
